spring:
  application:
    name: aop-idempotency-demo

  datasource:
    url: jdbc:postgresql://localhost:5433/aop_idempotency_demo
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # untuk demo bisa pakai update, di production sebaiknya none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true   # tampilkan query di console
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false

server:
  port: 8080
